### PR TITLE
Add first draft dd on bk

### PR DESCRIPTION
**Pull request by marcospedreiro**
Relatively new to reading financial statements, let me know what I can improve on. My plan is a couple of banks at a time and add them to the list.

### CODE REVIEW

**Comment by adwydman** [comment]
@joesocktwo @Cannabiz-420 can you guys take a look at this? I'll merge it if you guys approve the analysis.

**Comment by marcospedreiro** [comment]
Thanks @adwydman , if I've made any mistakes with the analysis please let me know and I'll correct it.

**Comment by adwydman** [comment]
@marcospedreiro Merged. I moved the BK.md file to Banking Fundamental Analysis folder.

**Comment by marcospedreiro** [comment]
Thanks!

**Pull request merged**
